parameters:
#    odysseus_back.example.class: Odysseus\BackBundle\Example

services:
#    odysseus_back.example:
#        class: %odysseus_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
